# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MAYWxkTrZu0gW

------WebKitFormBoundary7MAYWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3

------WebKitFormBoundary7MAYWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/ccf880d9-a055-4ebb-9328-8dd4539a37b9/transcription
Content-Type: application/json

{
    "prompt": "penhasco"
}

###

# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "ccf880d9-a055-4ebb-9328-8dd4539a37b9",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir:'''{transcription}''' "
}